@startuml
package BladeRondo
{
    package Card
    {
        class CardController

        class CardView

        abstract class Card
        {
            +string Name
            +string EffectText
            +int Cost
            +bool Limited
            +Sprite Face

            {abstract}+bool CanEffect();
            {abstract}+void Effect();
            {abstract}+bool CanPlay(int voltage);
            {abstract}+void Play();
        }

        package Effects
        {
            interface Effects
        }

        package SowrdCard
        {
            class Sword
        }

        package BreathCard
        {
            class Breath
        }
    }
}

package UnityEngine
{
    package EventSystems
    {
        interface IDragHandler
        interface IBeginDragHandler
        interface IEndDragHandler
    }
}

IBeginDragHandler<|..CardController
IDragHandler<|..CardController
IEndDragHandler<|..CardController


Card <|-- Sword
Sword ..|> Effects : 効果にそった物を実装
Card <|-- Breath
Breath ..|> Effects
@enduml