@startuml CardStateMacine

[*] --> None : ターン開始時
None --> Usable : プレイヤーのボルテージ\n>=カードのコスト
None --> Unusable : プレイヤーのボルテージ\n<=カードのコスト
Unusable --> None : ターン開始時
Usable --> SetResponce : カードタイプ=Trap
Usable --> Attack : カードタイプ=Physical or Magical
Usable --> AbilityActivate : カードタイプ=Support
SetResponce --> AbilityActivate : レスポンス発動
SetResponce --> ReturnHand : レスポンスが発動していない and ターン開始時
Attack --> AbilityActivate : 攻撃成功時
Attack --> ReturnHand : ターン終了時
Attack --> Discard
AbilityActivate --> ReturnHand
AbilityActivate --> Discard
AbilityActivate --> Follower
Follower --> AbilityActivate
ReturnHand --> None : ターン開始時

@enduml