@startuml
package BladeRondo
{
    package Game
    {
        package Component
        {
            package CardState
            {
                class None
                class Usable
                class Unusable
                class SetResponce
                class Attack
                class Attacked
                class ActivatableAbility
                class ActivatedAbility
                class Discard
            }
            class Card
            {
                +<<property>>Id:int{private set}
                +<<property>>Name:string{private set}
                +<<property>>AbilityText:string{private set}
                +<<property>>Cost:int{private set}
                +<<property>>Limited:bool{private set}
                +<<property>>Symbol:CardType{private set}
                +<<property>>AttackPower:int{private set}
                +<<property>>Responceable:List<CardTYpe>{private set}
                +<<property>>Face:Sprite{private set}
                --
                +<<delegate>>Ability():void
                +Abilities:Ability
                +<<delegate>>Check():bool
                +CanPlay:Check
                +CanActivateAbility:Check
                --
                Init(Id:int):void
            }
            class CardData
            {
                -id:int
                -name:string
                -abilityText:string
                -cost:int
                -limited:bool
                -symbol:CardType
                -attackPower:int
                -responceable:List<CardType>
                -face:Sprite
                +<<property>>Id:int{get only}
                +<<property>>Name:string{get only}
                +<<property>>AbilityText:string{get only}
                +<<property>>Cost:int{get only}
                +<<property>>Limited:bool{get only}
                +<<property>>Symbol:CardType{get only}
                +<<property>>AttackPower:int{get only}
                +<<property>>Responceable:List<CardType>{get only}
                +<<property>>Face:Sprite{get only}
            }
            class CardView
            {
                -Back:Sprite
                -Face:Image
                +ToggleFace(isFace:bool):void
            }
            class CardState
            {
                +<<property>>StatusType:CardStateType{private set}
                +<<property>>Status:IState
            }
            class CardController
            class CardAbilityUtil
            class CardPlayCheckUtil
            class CardAbilityCheckUtil
            class Hand
            class Graveyard
            class PlayArea
            enum CardStateType
            {
                None,
                Usable,
                Unusable,
                SetResponce,
                Attack,
                Attacked,
                ActivatableAbility,
                ActivatedAbility,
                Discard,
            }
            enum CardType
            {
                Breath
                Physical
                Magical
                Support
                Trap
            }
        }
        class CardFactory
    }
    package Network
    {
        package CustomProperties
        {
            package Players
            {
                class HP
                class "Attack "
                class Defence
                class Voltage

                class StartCheck
            }
            package Rooms
            {

            }
        }
        interface IConnecter
        class ServerConnecter
        class RoomConnecter
        class GameConnecter
        class RoomCreater
        class RoomExiter
        class RoomJoiner
    }
    package System
    {
        interface IFactory<T>
        {
            +Create(str:string):T
        }
        interface IState
        {
            +Execute():void
        }
        class DebugManager
        class TurnManager
    }
    package UI
    {
        class CardDropArea
        class RoomIdViewer
        class PlayerNode
        class GameStartChecker
    }
}

IState <|.down. None
IState <|.down. Usable
IState <|.down. Unusable
IState <|.down. Attack
IState <|.down. Attacked
IState <|.down. ActivatableAbility
IState <|.down. ActivatedAbility
IState <|.down. Discard
IState <|.down. SetResponce

IFactory <|.down. CardFactory
CardFactory .down.> Card : create
Card ..> CardData : read
Card ..> CardAbilityUtil : set delegate
Card ..> CardAbilityCheckUtil : set delegate
Card ..> CardPlayCheckUtil : set delegate
ScriptableObject <|-up- CardData
IBeginDragHandler <|.. CardController
IDragHandler <|.. CardController
IEndDrafHandler <|.. CardController
IDropHandler <|.. CardDropArea
PlayArea ..> Hand
Hand ..> PlayArea
Hand ..> Graveyard
PlayArea ..> Graveyard

IConnecter <|.. ServerConnecter
IConnecter <|.. RoomConnecter
IConnecter <|.. GameConnecter
@enduml